development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/payments/efetuado"
  email: bruformulasatibaia@uol.com.br

test:
  <<: *development

production:
  authenticity_token: 9CA8D46AF0C6177CB4C23D76CAF5E4B0
  email: bruformulasatibaia@uol.com.br
  return_to: "/payments/efetuado"
